project_id = "pmucsvrypogtttrajqxq"

[functions.test-email]
verify_jwt = false

[functions.send-user-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.sync-geo-layers]
verify_jwt = false

[functions.drone-weather]
verify_jwt = false

[functions.safesky-beacons]
verify_jwt = false

[functions.safesky-beacons-fetch]
verify_jwt = false

[functions.safesky-advisory]
verify_jwt = false

[functions.safesky-cron-refresh]
verify_jwt = false

[functions.check-document-expiry]
verify_jwt = false

[functions.check-maintenance-expiry]
verify_jwt = false

[functions.count-all-users]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.check-competency-expiry]
verify_jwt = false

[functions.check-mission-reminders]
verify_jwt = false

[functions.ai-risk-assessment]
verify_jwt = true

[functions.send-customer-welcome-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.send-user-approved-email]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.ai-search]
verify_jwt = true

[functions.auto-complete-missions]
verify_jwt = false

[functions.calendar-feed]
verify_jwt = false
