project_id = "pmucsvrypogtttrajqxq"

[functions.test-email]
verify_jwt = false

[functions.send-user-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.sync-geo-layers]
verify_jwt = false

[functions.drone-weather]
verify_jwt = false

[functions.safesky-beacons]
verify_jwt = false

[functions.safesky-advisory]
verify_jwt = false

[functions.safesky-cron-refresh]
verify_jwt = false

[functions.check-document-expiry]
verify_jwt = false

[functions.check-maintenance-expiry]
verify_jwt = false

[functions.count-all-users]
verify_jwt = false
