project_id = "pmucsvrypogtttrajqxq"

[functions.test-email]
verify_jwt = false

[functions.send-user-welcome-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.sync-geo-layers]
verify_jwt = false
